@startsalt
{
  {+
    <b>ASII-08
    ==
    .
    ✔
    <b>Traslado registrado
    correctamente
    .
    CAM-A-101 → limpieza
    CAM-B-204 → ocupada
    .
    .
    [Volver al inicio                  ]
  }
}
@endsalt
